name: "en_hi_nmt"
backend: "python"
max_batch_size: 512

input [
  {
    name: "INPUT_SENT_TOKENIZED"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "OUTPUT_SENT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

dynamic_batching {}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

response_cache {
  enable: true
}
